### ISSUE TITLE
1.0.0 - release tracker

### ISSUE THREAD

**Issue by luciorq** [luciorq/isoformic#10]
- [ ] Update processed transcript definition after gencode v43+ and mouse equivalent.
- [ ] Add support for edgeR-V4/catchSalmon column names.
- [ ] `prepare_profile_plot()` -- check table headers
- [ ] `plot_context()`, argument to filter isoform with low counts
- [ ] `plot_context()`, new argument for  manually selecting tx to plot`tx_names = c(tx_names)`
- [ ] Add an example to the README
- [x] Create examples in function docs
- [ ] Review examples
- [ ] context plot - add darker box border around exons
- [ ] context plot - Remove alpha legend
- [ ] context plot - Add Arrow for transcript direction
